spring:
  application:
    name: oauth2-demo
  redis:
    host: localhost
  freemarker:
    template-loader-path: classpath:/templates  #设定ftl文件路径
  mvc:
    static-path-pattern: /static/**     #设定静态文件路径，js,css等

server:
  port: 7779

security:
  oauth2:
    resource:
      filter-order: 3

logging:
  level:
    org.springframework: DEBUG    # 开启DEBUG日志
